sudo: true
dist: trusty
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
language: scala
scala: 2.11.8
jdk: oraclejdk8
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_7f5d77cd5a01_key -iv $encrypted_7f5d77cd5a01_iv
  -in continuousIntegrationStorage.json.enc -out /tmp/google_cloud_credentials.json -d
- openssl aes-256-cbc -K $encrypted_7f5d77cd5a01_key -iv $encrypted_7f5d77cd5a01_iv
  -in firebase.json.enc -out /tmp/firebase_credentials.json -d
env:
  matrix:
  - FIREBASE_SERVICE_ACCOUNT_KEY_LOCATION=/tmp/firebase_credentials.json
  - GOOGLE_CLOUD_KEY_LOCATION=/tmp/google_cloud_credentials.json
  - secure: sDTC6ktmqNHzTAgcAvVuJ4KqscO/6Mk2MVEgx7Qkd4E6+F9Wi70n1SLeLp7l60KZcejxwfrrOa2LS98j4NW8or6mH2GKokSG2Bl/atXSa3mUE5pCb/GtxLTHJN2ttAi+CQa0RVGpGINjPcksxyJ5EKv/abJqsdpp3uYUZBZ6tEV70pfYSRkDPM37YOvUN+rk8DkNuXXZVG/nVm87HqdX0FniL9/0LdLyrBXiLL76J6TgdS62+z53Uq7y8MlsaKZI3y5fosq6W+vOfVos2yUxuD2HzO6GoUOBsmQQgZHR5fRuQfSa9uj6iDksrOjx/8ro+EAGMG9zJpAI4I8K+A65SUnQBL8gR3DvP2zAi3dp5SGo9Wws8Sed+S85dLp41KzCT7/IjIXN0B9lGbiQyfSbX+edh8U54L7x/OSrO4Bx8S7jDfJFFux7k6Y4ZZN7WwBIf5YtH0/JvVfYMavwgVdh8vebthPgWwW1OR0UJg2jjPpDRiF4pRO2J2Vg+yj6h4QyKGlR5mXFLEVfzz6b6z6MqKBAIMU/PQFxbbdM9VsnJInXPzhR4IGKoMJ7Isz6oS39Uto96qrHt0UBcbMWJF7WwFm6i+mlX3TtM1/DaCaAza6vTnLW6LLJ54mskpJhmLSs2/sNjYAPKkvQkfhD8EzkSkREVbRlUXK5BkfwgedKojE=
  global:
    secure: Be9RBdqZM+nhaHr1r329ijFAw8Nzn0tJlM2hUr7ZGGjm4gG0WXQ+4HruqwmMCfr60nhC3vhTbGtVEPZp+y3zJofAA7A0YHlOSBHanR+OI1oJai+leKbN/hhR7nvVYXl5psrDOlN6lXxjmcZrqOwvX61iG9NZc338oGW2tp6pOdeRFL4qwUMQpPwpfIlJnEr4brf9bfE6YGM6J70U/hZsTfI96RI6bInI3ao2OIkU4438E8pM1sEdjih7zzC9eBYkLlzQxX38/45rK88CELGZT6OUjh8Y3ABA5VrDKJZw1TOPea981jeo0jrHoaXfVtc1nEDeCrHWaCzo7m5tLf3WKRoe4dUnXu5kbm2DxxlqZ6oh+XaMs+ow+KMpIa0naxy2bBfrYCZVzcyU1KYG/KIG8cYyMMp8nj6oH5EsK+aUDbC893ieM30TOIbgQGJKEh6ssZ8sopeB+9CFqsvgSTSQnYaiJmtC9B2w4eZqNYWvjYusa6vjAhgIfQD8UoYvrPv0Z7vS8ZP7YMSvX0GcMwW7Z8u5V1tgNWHUZiL3jtzm1lb3r0U/4O333Wpaf89LNMyw9fJOs3ZU90qEkZU+VPUONbNLGnOShnvEu4sMN68HEaKQHEq8YuVk8e2DgUAq76JKwXSI+8I53RsNT8cx8yCcFPkUZjvl92VNap1LtRWo/I8=
